// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0XzASrEuLxgMPEWSMs7G595K7x4cyIo',
    appId: '1:758674659257:web:6436604ae4ee56d0010868',
    messagingSenderId: '758674659257',
    projectId: 'rafeeq-app-92835',
    authDomain: 'rafeeq-app-92835.firebaseapp.com',
    storageBucket: 'rafeeq-app-92835.firebasestorage.app',
    measurementId: 'G-M21L9KRKP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkuO83-7D3LxmC9YGBqWvLfZGQps4padE',
    appId: '1:758674659257:android:4d5582b85ddd736f010868',
    messagingSenderId: '758674659257',
    projectId: 'rafeeq-app-92835',
    storageBucket: 'rafeeq-app-92835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyOS-9pUxT7OKjjfEEXVphdKm4qcJz5k',
    appId: '1:758674659257:ios:acff915a5438945f010868',
    messagingSenderId: '758674659257',
    projectId: 'rafeeq-app-92835',
    storageBucket: 'rafeeq-app-92835.firebasestorage.app',
    iosBundleId: 'com.example.rafeeq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCyOS-9pUxT7OKjjfEEXVphdKm4qcJz5k',
    appId: '1:758674659257:ios:acff915a5438945f010868',
    messagingSenderId: '758674659257',
    projectId: 'rafeeq-app-92835',
    storageBucket: 'rafeeq-app-92835.firebasestorage.app',
    iosBundleId: 'com.example.rafeeq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0XzASrEuLxgMPEWSMs7G595K7x4cyIo',
    appId: '1:758674659257:web:ec173f5e2856da08010868',
    messagingSenderId: '758674659257',
    projectId: 'rafeeq-app-92835',
    authDomain: 'rafeeq-app-92835.firebaseapp.com',
    storageBucket: 'rafeeq-app-92835.firebasestorage.app',
    measurementId: 'G-BM0N1QQ29K',
  );
}
